"""Create relationship between player and goal

Revision ID: 01c8ce3d373c
Revises: 35fe01acae4d
Create Date: 2020-11-25 13:14:17.621228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01c8ce3d373c'
down_revision = '35fe01acae4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('scorer_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'goals', 'players', ['scorer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_column('goals', 'scorer_id')
    # ### end Alembic commands ###
