"""Delete column player from table goal

Revision ID: 050d8758a777
Revises: 4d2c038fdcde
Create Date: 2020-11-26 15:26:25.722848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050d8758a777'
down_revision = '4d2c038fdcde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'player')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('player', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
