"""Rename table match to matches

Revision ID: 265544c44426
Revises: d346db27b2b3
Create Date: 2020-11-17 16:48:51.388597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '265544c44426'
down_revision = 'd346db27b2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('team_1', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('team_2', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('goal_1', sa.Integer(), nullable=False),
    sa.Column('goal_2', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('match')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_1', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('team_2', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('goal_1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goal_2', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='match_pkey')
    )
    op.drop_table('matches')
    # ### end Alembic commands ###
