"""Create relationship between team and player

Revision ID: 2ab8c4e6e489
Revises: bf873edcecda
Create Date: 2020-12-19 01:18:37.712002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ab8c4e6e489'
down_revision = 'bf873edcecda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('tournament_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'teams', 'tournaments', ['tournament_id'], ['id'])
    op.drop_column('teams', 'day')
    op.drop_column('teams', 'players')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('players', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('day', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'tournament_id')
    # ### end Alembic commands ###
