"""Change name and type of column championship to day on table goals

Revision ID: 35fe01acae4d
Revises: 8ab261e217e8
Create Date: 2020-11-21 01:27:20.688255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35fe01acae4d'
down_revision = '8ab261e217e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('day', sa.Date(), nullable=True))
    op.drop_column('goals', 'championship')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('championship', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('goals', 'day')
    # ### end Alembic commands ###
