"""Correction on the foreignkey of table goals

Revision ID: 4d2c038fdcde
Revises: 6f5d5771bfcb
Create Date: 2020-11-26 00:28:29.914071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d2c038fdcde'
down_revision = '6f5d5771bfcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('player_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('goals_scorer_id_fkey', 'goals', type_='foreignkey')
    op.create_foreign_key(None, 'goals', 'players', ['player_id'], ['id'])
    op.drop_column('goals', 'scorer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('scorer_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.create_foreign_key('goals_scorer_id_fkey', 'goals', 'players', ['scorer_id'], ['id'])
    op.drop_column('goals', 'player_id')
    # ### end Alembic commands ###
