"""Create table match

Revision ID: d346db27b2b3
Revises: ed0934f3869e
Create Date: 2020-11-17 16:46:43.101641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd346db27b2b3'
down_revision = 'ed0934f3869e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('team_1', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('team_2', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('goal_1', sa.Integer(), nullable=False),
    sa.Column('goal_2', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
