"""create table goal

Revision ID: ed0934f3869e
Revises: 2c7dd2077355
Create Date: 2020-11-04 21:26:59.882410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed0934f3869e'
down_revision = '2c7dd2077355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('player', sa.String(length=255), nullable=True),
    sa.Column('championship', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals')
    # ### end Alembic commands ###
