"""rename player table

Revision ID: ee4a10edf24a
Revises: 1592ae44e726
Create Date: 2020-11-02 17:24:06.719044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee4a10edf24a'
down_revision = '1592ae44e726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('jogadores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jogadores',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='jogadores_pkey')
    )
    op.drop_table('players')
    # ### end Alembic commands ###
